[pytest]
# Opciones de pytest
addopts = --html=reports/report.html --self-contained-html -v
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Variables de entorno
env = test

# Logs
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(name)s: %(message)s

# Reportes
markers =
    ui: marca para pruebas UI
    api: marca para pruebas API
    smoke: marca para pruebas de humo
    regression: marca para pruebas de regresión

# Ignorar directorios
norecursedirs = .git .venv __pycache__ logs reports screenshots
